version: 2
updates:
- package-ecosystem: maven
  directory: "/"
  schedule:
    interval: daily
    time: "04:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: org.owasp:dependency-check-maven
    versions:
    - 6.1.4
  - dependency-name: org.springframework.boot:spring-boot-starter-parent
    versions:
    - 2.4.4
  - dependency-name: org.pitest:pitest-maven
    versions:
    - 1.6.4
  - dependency-name: org.springframework.boot:spring-boot-maven-plugin
    versions:
    - 2.4.4
